# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Natalie Lung
description: > # this means to ignore newlines until "baseurl:"
  A Portfolio
repository: https://github.com/natlungfy/natlungfy.github.io
baseurl:  # the subpath of your site, e.g. /blog
url: http://natalielung.com  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Natalie Lung
email: hi@natalielung.com

navigation:
  - text: Home
    url: /
  - text: Portfolio
    url: /portfolio
  - text: Community Projects
    url: /affiliations
  - text: Resume
    url: /Natalie_Lung_CV.pdf

projects:
  - name: Forbes Asia Graphics
    description: Graphics for Asia-focused stories such as electric vehicles, the Shinzo Abe scandal, 30 Under 30 Asia, Netflix vs. Amazon in India
    inlink: http://natalielung.com/portfolio/forbes.html
    tech: Illustrator, Photoshop, CartoDB
    image: http://natalielung.com/images/forbes.gif
  - name: MIT Media Lab, Center for Civic Media - Media Cloud
    description: Implemented Chinese natural language processing on Media Cloud, a text aggregator tool that monitors and analyzes media coverage and the relationships between influential news sources andstories. Curated Greater China news sources. Thumbnail shows text analysis for Xi Jinping. 
    tech: Python, NLTK, jieba, Ubuntu, VirtualBox
    link: https://mediacloud.org/
    image: https://miro.medium.com/fit/c/262/262/2*sAg1ZS1GKVLBZoITntVriA@2x.png
  - name: South China Morning Post - Electing the Chief Executive
    description: Multimedia visual guide to Hong Kong’s political reform vote in 2015. Prepped data for interactive graphic and contributed text.
    tech: ArchieML, Google Sheets
    link: http://multimedia.scmp.com/hong-kong-election-2017/
    image: http://natalielung.com/images/scmpvote.png
  - name: South China Morning Post - Hong Kong’s wall trees
    description: Infographic of everything you need to know about the banyans that define the city’s landscape. Contributed research and graphic concept.
    link: http://www.scmp.com/infographics/article/1845412/hong-kongs-wall-trees-everything-you-need-know-about-banyans-define
    image: http://natalielung.com/images/scmptrees.PNG
  - name: Mementos from the U.S.
    description: Interactive website about my exchange semester in the US. Final project for web development course at Mizzou.
    link: http://natalielung.com/projects/mementos
    tech: HTML, CSS, Javascript, jQuery, JSON, PHP
    github: https://github.com/natlungfy/natlungfy.github.io/tree/master/projects/mementos
    image: http://natalielung.com/images/mementosGIF.gif
  - name: Office Escape
    description: An endless runner mobile game where players tilt their devices to avoid obstacles. Best viewed on a gyroscope-equipped Android device with device orientation locked. Final project for computer graphics course at Mizzou.
    tech: HTML, CSS, Javascript, Phaser, gyro.js
    link: https://www.youtube.com/watch?v=gEiLgBrf2n8
    github: https://github.com/cg-mobilegame/cg-mobilegame.github.io
    image: http://natalielung.com/images/officeesc.gif
  - name: Hong Kong Shophouse
    description: Multimedia reporting group project about Hong Kong's historical tenement buildings.
    tech: Timeline.js, Google Maps, photosphere, infographics
    link: http://hkshophouse.wixsite.com/home/
    image: http://natalielung.com/images/shophouse.png
  - name: In 360 - Before & After A New Subway Station
    description: Multimedia reporting project using 360 photos and videos about the changes to a Hong Kong neighborhood after the opening of a subway station.
    tech: HTML, Google Maps, Contributed photospheres to Google Street View
    link: https://natlungfy.wordpress.com/2016/11/03/whampoa-before-and-after-in-360
    image: https://natlungfy.files.wordpress.com/2016/11/mtr.jpg?w=1200&h=800&crop=1

social:
  - service: twitter
    username: natlungfy
    link: https://twitter.com/natlungfy
  - service: instagram
    username: natlungfy
    link: https://instagram.com/natlungfy
  - service: youtube
    username: natlungfy
    link: https://youtube.com/user/natlungfy
  - service: linkedin
    username: natlungfy
    link: https://linkedin.com/in/natlungfy
  - service: github
    username: natlungfy
    link: https://github.com/natlungfy

# Plugins
gems:
  - jekyll-seo-tag
