# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Natalie Lung
description: > # this means to ignore newlines until "baseurl:"
  A Portfolio
repository: https://github.com/natlungfy/natlungfy.github.io
baseurl:  # the subpath of your site, e.g. /blog
url: http://natalielung.xyz  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Natalie Lung
email: nat@natalielung.xyz

navigation:
  - text: Home
    url: /
  - text: Work
    url: /work
  - text: Community Work
    url: /community
  - text: Resume
    url: /Natalie_Lung_CV.pdf
  - text: Blog
    url: /blog

projects:
  - name: Electing the Chief Executive
    description: Multimedia visual guide Hong Kong’s political reform voted down. Contributed text and prepped data for interactive graphic.
    link: http://multimedia.scmp.com/hong-kong-election-2017/
    image: http://natalielung.xyz/images/scmpvote.png
  - name: Hong Kong’s wall trees
    description: Infographic of everything you need to know about the banyans that define the city’s landscape. Contributed research and graphic concept
    link: http://www.scmp.com/infographics/article/1845412/hong-kongs-wall-trees-everything-you-need-know-about-banyans-define#comments
    image: http://natalielung.xyz/images/scmptrees.png
  - name: Shophouse
    description: Multimedia reporting group project about Hong Kong's historical tenement buildings. [Timeline.js, Google Maps, photosphere, infographics]
    link: http://hkshophouse.wixsite.com/home/
    image: http://natalielung.xyz/images/shophouse.png
  - name: In 360 - Whampoa through the years, before and after the MTR Station
    description: Multimedia reporting project [Google Maps, photospheres]
    link: https://natlungfy.wordpress.com/2016/11/03/whampoa-before-and-after-in-360
    image: https://natlungfy.files.wordpress.com/2016/11/mtr.jpg?w=1200&h=800&crop=1
  - name: Photojournalism in the age of smartphones - AFP Pedro Ugarte
    description: Video interview with AFP Photo Director [Edited with Premiere]
    link: https://www.youtube.com/watch?v=HexekAo3pNQ
    image: http://i3.ytimg.com/vi/HexekAo3pNQ/hqdefault.jpg
  - name: Siu Fung
    description: Documentary group project about a transgender bodybuilder. Won Grand Prize at the TVB Inter-Collegiate Documentary Competition [Edited with Premiere]
    link: https://www.youtube.com/watch?v=MdMy4zuZdok
    image: http://i3.ytimg.com/vi/MdMy4zuZdok/hqdefault.jpg

social:
  - service: github
    username: natlungfy
    link: https://github.com/natlungfy
  - service: twitter
    username: natlungfy
    link: https://twitter.com/natlungfy
  - service: instagram
    username: natlungfy
    link: https://instagram.com/natlungfy

# Plugins
gems:
  - jekyll-seo-tag
