# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Natalie Lung
description: > # this means to ignore newlines until "baseurl:"
  A Portfolio
repository: https://github.com/natlungfy/natlungfy.github.io
baseurl:  # the subpath of your site, e.g. /blog
url: http://natalielung.xyz  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Natalie Lung
email: nat@natalielung.xyz

navigation:
  - text: Home
    url: /
  - text: Work
    url: /work
  - text: Community Work
    url: /community
  - text: Resume
    url: /Natalie_Lung_CV.pdf
  - text: Blog
    url: /blog

projects:
  # - name: git-secret
  #   description: A bash-tool to store your private data inside a git repository.
  #   link: https://sobolevn.github.io/git-secret
  #   image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true

social:
  - service: github
    username: natlungfy
    link: https://github.com/natlungfy
  - service: twitter
    username: natlungfy
    link: https://twitter.com/natlungfy
  - service: instagram
    username: natlungfy
    link: https://instagram.com/natlungfy

# Plugins
gems:
  - jekyll-seo-tag
