# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Natalie Lung
description: > # this means to ignore newlines until "baseurl:"
  A Portfolio
repository: https://github.com/natlungfy/natlungfy.github.io
baseurl:  # the subpath of your site, e.g. /blog
url: http://natalielung.xyz  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Natalie Lung
email: nat@natalielung.xyz

navigation:
  - text: Home
    url: /
  - text: Media Work
    url: /portfolio
  - text: Community Work
    url: /community
  - text: Resume
    url: /Natalie_Lung_CV.pdf
  - text: Blog
    url: /blog

projects:
  - name: South China Morning Post - Electing the Chief Executive
    description: Multimedia visual guide to Hong Kong’s political reform vote in 2015. Prepped data for interactive graphic and contributed text. [ArchieML, Google Sheets]
    link: http://multimedia.scmp.com/hong-kong-election-2017/
    image: http://natalielung.xyz/images/scmpvote.png
  - name: South China Morning Post - Hong Kong’s wall trees
    description: Infographic of everything you need to know about the banyans that define the city’s landscape. Contributed research and graphic concept.
    link: http://www.scmp.com/infographics/article/1845412/hong-kongs-wall-trees-everything-you-need-know-about-banyans-define
    image: http://natalielung.xyz/images/scmptrees.PNG
  - name: Droste - Rent Control
    description: Negotiate with your landlord using data whenever he proposes an unrealistic rent increase. This public service tool generates a graph of historical rent prices of your district and an email template. [Plotly.JS, Semantic UI]
    link: http://droste.hk
    image: http://natalielung.xyz/images/rentcontrol.png
  - name: Shophouse
    description: Multimedia reporting group project about Hong Kong's historical tenement buildings. [Timeline.js, Google Maps, photosphere, infographics]
    link: http://hkshophouse.wixsite.com/home/
    image: http://natalielung.xyz/images/shophouse.png
  - name: In 360 - Whampoa through the years, before and after the MTR Station
    description: Multimedia reporting project [Google Maps, photospheres]
    link: https://natlungfy.wordpress.com/2016/11/03/whampoa-before-and-after-in-360
    image: https://natlungfy.files.wordpress.com/2016/11/mtr.jpg?w=1200&h=800&crop=1

social:
  - service: github
    username: natlungfy
    link: https://github.com/natlungfy
  - service: twitter
    username: natlungfy
    link: https://twitter.com/natlungfy
  - service: instagram
    username: natlungfy
    link: https://instagram.com/natlungfy

# Plugins
gems:
  - jekyll-seo-tag
